  select* from customer

--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum([purchase_amount_(usd)]) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,[purchase_amount_(usd)]
from customer
where discount_applied='Yes'and [purchase_amount_(usd)]>=(select avg([purchase_amount_(usd)]) from customer)

--Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,round(AVG(review_rating),2) as "Average product rating"
from customer
group by item_purchased
order by "Average Product Rating" desc



--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,round(avg([purchase_amount_(usd)]),2) as "Average purchase Amount"
from customer
where shipping_type in('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as "Total Count",
round(avg([purchase_amount_(usd)]),3) as "avg spend",
round(sum([purchase_amount_(usd)]),3) as "Total Revenue"
from customer
group by subscription_status
order by [avg spend],[Total Revenue]

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased as "Product",
round(sum(case when discount_applied='Yes'then 1.0 else 0.0 end)/count(*) *100,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id ,previous_purchases,
case 
when previous_purchases=1 then'New'
when previous_purchases between 2 and 10 then'Returning'
else'Loyal'
end as customer_segment
from customer
)
select customer_segment,count(*) as "Number of customers"
from customer_type
group by customer_segment
order by [Number of customers] desc
--Q8. What are the top 3 most purchased products within each category?
with item_counts as(
    select category, item_purchased,
    count(customer_id) as total_orders,
    row_number() over (partition by category order by count(customer_id) desc) as item_rank
    from customer
    group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as "repeat buyers"
from customer
where previous_purchases>5
group by subscription_status
--Q10. What is the revenue contribution of each age group?
select 
age_group,sum([purchase_amount_(usd)]) as "Total_revenue"
from customer 
group by age_group
order by total_revenue desc